import type { ToolCategory, ToolDefinition } from "./types.js";

export type { ToolCategory, ToolTier, ToolKind, ToolDefinition } from "./types.js";

export const TOOL_CATEGORIES: Record<
  ToolCategory,
  { label: string; description: string }
> = {
  pdf: {
    label: "PDF Tools",
    description: "Merge, split, compress, convert, and secure PDF files",
  },
  image: {
    label: "Image Converter",
    description: "Compress, resize, crop, and convert images",
  },
  text: {
    label: "Text Tools",
    description: "Convert documents, markdown, and plain text",
  },
  developer: {
    label: "Developer Tools",
    description: "JSON, Base64, URL encoding, and SHA-256 — private in-browser utilities",
  },
  calculator: {
    label: "Calculators",
    description:
      "Percentage, age, BMI, and unit conversions — instant results in your browser",
  },
};

/** Popular tools shown on homepage (matches Figma CONVERTHUB grid) */
export const POPULAR_TOOL_SLUGS: string[] = [
  "pdf-to-word",
  "merge-pdf",
  "compress-pdf",
  "compress-image",
  "jpg-to-pdf",
  "pdf-to-jpg",
  "word-to-pdf",
  "split-pdf",
  "jpg-to-png",
  "png-to-jpg",
  "pdf-to-excel",
  "ocr-pdf",
];

const pdfAccept = ["application/pdf"];

export const TOOLS: ToolDefinition[] = [
  // ─── PDF Tools ───────────────────────────────────────────────
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one document",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 20,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF into separate files by page ranges",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "remove-pages",
    name: "Remove Pages",
    description: "Delete selected pages from a PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 2,
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Extract specific pages into a new PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 2,
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    description: "Reorder pages in your PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 2,
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate all or selected pages",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 2,
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to JPG images",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert PDF pages to PNG images",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 2,
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG images into a PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 20,
    maxMb: 50,
    accept: ["image/jpeg", "image/jpg"],
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "png-to-pdf",
    name: "PNG to PDF",
    description: "Convert PNG images into a PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 20,
    maxMb: 50,
    accept: ["image/png"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 100,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 4,
  },
  {
    slug: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    description: "Convert PDF to archival PDF/A format",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 4,
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Best-effort repair of corrupted PDFs",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 4,
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF to editable DOCX",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 5,
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Convert PDF to PPTX",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: pdfAccept,
    enabled: true,
    phase: 5,
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Convert PDF to XLSX",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 5,
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert DOCX to PDF",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/msword",
    ],
    enabled: true,
    popular: true,
    phase: 5,
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert PPTX to PDF",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: [
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "application/vnd.ms-powerpoint",
    ],
    enabled: true,
    phase: 5,
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert XLSX to PDF",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel",
    ],
    enabled: true,
    phase: 5,
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert HTML content to PDF",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 5,
    accept: ["text/html"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract plain text from a PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 2,
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add text watermark to every page",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 6,
  },
  {
    slug: "page-numbers",
    name: "Add Page Numbers",
    description: "Add page numbers to your PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 6,
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Crop margins from PDF pages",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 6,
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Cover regions with black boxes",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 6,
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Place a signature image on your PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 2,
    maxMb: 50,
    accept: ["application/pdf", "image/png", "image/jpeg"],
    enabled: true,
    phase: 6,
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection to a PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 6,
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password from a PDF you own",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 6,
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    popular: true,
    phase: 7,
  },
  {
    slug: "compare-pdf",
    name: "Compare PDF",
    description: "Compare two PDF documents",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 2,
    maxMb: 50,
    accept: pdfAccept,
    enabled: true,
    phase: 7,
  },
  {
    slug: "image-to-word",
    name: "Image to Word",
    description: "OCR image text into a Word document",
    category: "pdf",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: ["image/jpeg", "image/png", "image/jpg"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "scan-to-pdf",
    name: "Scan to PDF",
    description: "Turn phone photos or scans into a PDF",
    category: "pdf",
    tier: "sync",
    kind: "file",
    maxFiles: 20,
    maxMb: 50,
    accept: ["image/jpeg", "image/png", "image/jpg"],
    enabled: true,
    phase: 2,
  },

  // ─── Image Converter ─────────────────────────────────────────
  {
    slug: "compress-image",
    name: "Compress Image",
    description: "Reduce image file size while keeping quality",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/jpeg", "image/png", "image/webp", "image/jpg"],
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    description: "Resize images to exact width and height",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/jpeg", "image/png", "image/webp", "image/jpg"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    description: "Crop images to a custom region",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/jpeg", "image/png", "image/webp", "image/jpg"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    description: "Rotate images 90°, 180°, or 270°",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/jpeg", "image/png", "image/webp", "image/jpg"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    description: "Convert JPEG photos to PNG format",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/jpeg", "image/jpg"],
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    description: "Convert PNG images to JPEG format",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/png"],
    enabled: true,
    popular: true,
    phase: 2,
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    description: "Convert WebP images to JPEG",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/webp"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "jpg-to-webp",
    name: "JPG to WebP",
    description: "Convert JPEG images to WebP",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/jpeg", "image/jpg"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPG",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/heic", "image/heif"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "gif-to-png",
    name: "GIF to PNG",
    description: "Convert GIF frames to PNG (first frame)",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: ["image/gif"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "bmp-to-jpg",
    name: "BMP to JPG",
    description: "Convert bitmap images to JPEG",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/bmp"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    description: "Rasterize SVG vector graphics to PNG",
    category: "image",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 10,
    accept: ["image/svg+xml"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "avif-to-jpg",
    name: "AVIF to JPG",
    description: "Convert AVIF images to JPEG",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 10,
    maxMb: 25,
    accept: ["image/avif"],
    enabled: true,
    phase: 2,
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Combine any images into one PDF",
    category: "image",
    tier: "sync",
    kind: "file",
    maxFiles: 20,
    maxMb: 50,
    accept: ["image/jpeg", "image/png", "image/webp", "image/jpg", "image/gif"],
    enabled: true,
    phase: 2,
  },

  // ─── Text Tools ──────────────────────────────────────────────
  {
    slug: "txt-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text files to PDF",
    category: "text",
    tier: "sync",
    kind: "file",
    maxFiles: 1,
    maxMb: 5,
    accept: ["text/plain"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "markdown-to-pdf",
    name: "Markdown to PDF",
    description: "Convert Markdown files to PDF",
    category: "text",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 5,
    accept: ["text/markdown", "text/plain"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "markdown-to-word",
    name: "Markdown to Word",
    description: "Convert Markdown to DOCX",
    category: "text",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 5,
    accept: ["text/markdown", "text/plain"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "rtf-to-pdf",
    name: "RTF to PDF",
    description: "Convert Rich Text Format to PDF",
    category: "text",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: ["application/rtf", "text/rtf"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "tex-to-word",
    name: "LaTeX to Word",
    description: "Convert LaTeX documents to DOCX",
    category: "text",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 10,
    accept: ["application/x-tex", "text/plain"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "pages-to-word",
    name: "Pages to Word",
    description: "Convert Apple Pages to DOCX",
    category: "text",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 25,
    accept: ["application/vnd.apple.pages"],
    enabled: true,
    phase: 5,
  },
  {
    slug: "epub-to-pdf",
    name: "EPUB to PDF",
    description: "Convert e-books to PDF",
    category: "text",
    tier: "async",
    kind: "file",
    maxFiles: 1,
    maxMb: 50,
    accept: ["application/epub+zip"],
    enabled: true,
    phase: 5,
  },

  // ─── Developer Tools ─────────────────────────────────────────
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format and validate JSON data",
    category: "developer",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "base64-encode",
    name: "Base64 Encode",
    description: "Encode text to Base64",
    category: "developer",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "base64-decode",
    name: "Base64 Decode",
    description: "Decode Base64 to text",
    category: "developer",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "url-encode",
    name: "URL Encode",
    description: "Percent-encode text for URLs",
    category: "developer",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "url-decode",
    name: "URL Decode",
    description: "Decode percent-encoded URLs",
    category: "developer",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5 and SHA-256 hashes",
    category: "developer",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },

  // ─── Calculators ─────────────────────────────────────────────
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages and changes",
    category: "calculator",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate age from birth date",
    category: "calculator",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate body mass index",
    category: "calculator",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, and temperature",
    category: "calculator",
    tier: "sync",
    kind: "utility",
    maxFiles: 0,
    maxMb: 1,
    accept: [],
    enabled: true,
    phase: 8,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getEnabledTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.enabled);
}

export function getPopularTools(): ToolDefinition[] {
  return POPULAR_TOOL_SLUGS.map((slug) => getToolBySlug(slug)).filter(
    (t): t is ToolDefinition => !!t && t.enabled
  );
}
